ln -s bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.eot app/assets/fonts/glyphicons-halfings-regular.eot
ln -s bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.svg app/assets/fonts/glyphicons-halfings-regular.svg
ln -s bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf app/assets/fonts/glyphicons-halfings-regular.ttf
ln -s bower_components/bootstrap/dist/fonts/glyphicons-halflings-regular.woff app/assets/fonts/glyphicons-halfings-regular.woff
ln -s bower_components/font-awesome/fonts/FontAwesome.otf app/assets/fonts/FontAwesome.otf
ln -s bower_components/font-awesome/fonts/fontawesome-webfont.eot app/assets/fonts/fontawesome-webfont.eot
ln -s bower_components/font-awesome/fonts/fontawesome-webfont.svg app/assets/fonts/fontawesome-webfont.svg
ln -s bower_components/font-awesome/fonts/fontawesome-webfont.ttf app/assets/fonts/fontawesome-webfont.ttf
ln -s bower_components/font-awesome/fonts/fontawesome-webfont.woff app/assets/fonts/fontawesome-webfont.woff
